### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by billyvg** [tapayne88/yarn-pnp-demo#1]
I'm trying out this demo repo and it's not working for me locally...

![image](https://user-images.githubusercontent.com/79684/140538160-ff7b7a01-2ed2-4423-9b35-d3e345b97319.png)

Opening up `App.tsx`:
![image](https://user-images.githubusercontent.com/79684/140538239-a780f2fa-3a1d-4062-bf18-181bbc499106.png)

I have lspconfig configured (and it works fine in a non pnp repo).

**Comment by tapayne88** [comment]
Hi @billyvg 👋 

It is working for me 😬 Looking at the errors it looks like your `filetype` may be off or perhaps the LSP can't resolve the `tsconfig.json` file.

What does you config look like?

You can find my TypeScript LSP config over here
https://github.com/tapayne88/dotfiles/blob/master/dot_config/nvim/lua/tap/lsp/servers/typescript.lua

**Comment by billyvg** [comment]
Thanks @tapayne88 I'll poke around your config - this is my `LspInfo` 
![image](https://user-images.githubusercontent.com/79684/142255916-2f8a16f9-1cad-4234-9051-ffa410d44e68.png)

**Comment by tapayne88** [comment]
There is also the yarn docs for setting up neovim LSP
https://yarnpkg.com/getting-started/editor-sdks#neovim-native-lsp

Specifically, you'll need to have setup the TypeScript SDK for the language server to work with PnP
```bash
yarn dlx @yarnpkg/sdks base
```

Give me a shout if it's still not working!

**Comment by billyvg** [comment]
I'm going to close this - I still haven't figured it out, but I assume there's something config-wise I'm missing. I'll revisit this when I get a chance. Thanks for your help!
